"""20 hand-written denial_profiles so Person B can build immediately."""

from schema import DETERMINATION_OVERTURNED, DETERMINATION_UPHELD

FIXTURE_PROFILES = [
    {
        "source_ref": "FIX-001",
        "determination": DETERMINATION_OVERTURNED,
        "segment": {
            "diagnosis_category": "Orthopedic/Musculoskeletal",
            "treatment_category": "Pharmacy",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Pharmacy",
        "reasoning_pattern": "Reviewer found the preferred NSAID had already failed and the requested biologic met guideline criteria.",
        "strategy_keys": ["failed_preferred_alternative"],
        "evidence_keys": ["treating_physician_attestation"],
        "summary_text": "Patient with rheumatoid arthritis was denied Humira as not medically necessary after the plan required trial of methotrexate and NSAIDs first.",
    },
    {
        "source_ref": "FIX-002",
        "determination": DETERMINATION_UPHELD,
        "segment": {
            "diagnosis_category": "Orthopedic/Musculoskeletal",
            "treatment_category": "Durable Medical Equipment",
            "denial_type": "Medical Necessity",
        },
        "service_type": "DME/Prosthetics",
        "reasoning_pattern": "Record lacked documented functional limitation that would make a custom brace necessary over an off-the-shelf device.",
        "strategy_keys": ["functional_limitation_documented"],
        "evidence_keys": ["physical_exam_findings"],
        "summary_text": "Patient with knee osteoarthritis was denied a custom unloader brace as not medically necessary; plan said OTC bracing was appropriate.",
    },
    {
        "source_ref": "FIX-003",
        "determination": DETERMINATION_OVERTURNED,
        "segment": {
            "diagnosis_category": "Mental Health",
            "treatment_category": "Mental Health Treatment",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Mental Health",
        "reasoning_pattern": "Residential level of care was justified by recent suicide attempt and failed IOP.",
        "strategy_keys": ["failed_lower_level_of_care"],
        "evidence_keys": ["hospitalization_records"],
        "summary_text": "Adolescent with major depression was denied residential psychiatric treatment as not medically necessary after an emergency department visit for suicidal ideation.",
    },
    {
        "source_ref": "FIX-004",
        "determination": DETERMINATION_UPHELD,
        "segment": {
            "diagnosis_category": "Mental Health",
            "treatment_category": "Mental Health Treatment",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Mental Health",
        "reasoning_pattern": "Outpatient therapy twice weekly was available and the record did not show need for PHP intensity.",
        "strategy_keys": ["failed_lower_level_of_care"],
        "evidence_keys": ["treating_physician_attestation"],
        "summary_text": "Adult with generalized anxiety was denied partial hospitalization as not medically necessary; plan offered weekly outpatient therapy.",
    },
    {
        "source_ref": "FIX-005",
        "determination": DETERMINATION_OVERTURNED,
        "segment": {
            "diagnosis_category": "Cancer",
            "treatment_category": "Diagnostic Imaging",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Diagnostic Imaging",
        "reasoning_pattern": "PET-CT was indicated to stage a newly diagnosed lymphoma per NCCN.",
        "strategy_keys": ["standard_of_care_guideline"],
        "evidence_keys": ["named_clinical_guideline"],
        "summary_text": "Patient with newly diagnosed lymphoma was denied PET-CT staging as not medically necessary; plan said CT alone was sufficient.",
    },
    {
        "source_ref": "FIX-006",
        "determination": DETERMINATION_UPHELD,
        "segment": {
            "diagnosis_category": "Cancer",
            "treatment_category": "Pharmacy",
            "denial_type": "Experimental/Investigational",
        },
        "service_type": "Pharmacy",
        "reasoning_pattern": "Off-label immunotherapy lacked supporting literature for this tumor type.",
        "strategy_keys": ["peer_reviewed_literature"],
        "evidence_keys": ["published_studies"],
        "summary_text": "Patient with metastatic sarcoma was denied an off-label checkpoint inhibitor as experimental/investigational.",
    },
    {
        "source_ref": "FIX-007",
        "determination": DETERMINATION_OVERTURNED,
        "segment": {
            "diagnosis_category": "Endocrine/Metabolic",
            "treatment_category": "Pharmacy",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Pharmacy",
        "reasoning_pattern": "CGM was medically necessary given recurrent hypoglycemia on insulin.",
        "strategy_keys": ["safety_risk_if_denied"],
        "evidence_keys": ["lab_and_glucose_logs"],
        "summary_text": "Type 1 diabetic was denied a continuous glucose monitor as not medically necessary; plan required fingersticks only.",
    },
    {
        "source_ref": "FIX-008",
        "determination": DETERMINATION_UPHELD,
        "segment": {
            "diagnosis_category": "Endocrine/Metabolic",
            "treatment_category": "Pharmacy",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Pharmacy",
        "reasoning_pattern": "A1c was at goal on metformin; GLP-1 did not meet step-therapy criteria.",
        "strategy_keys": ["failed_preferred_alternative"],
        "evidence_keys": ["lab_and_glucose_logs"],
        "summary_text": "Type 2 diabetic with A1c 6.4% was denied Ozempic as not medically necessary pending trial of preferred formulary agents.",
    },
    {
        "source_ref": "FIX-009",
        "determination": DETERMINATION_OVERTURNED,
        "segment": {
            "diagnosis_category": "Infectious Disease",
            "treatment_category": "Pharmacy",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Pharmacy",
        "reasoning_pattern": "Genotype and fibrosis stage met AASLD criteria for direct-acting antivirals.",
        "strategy_keys": ["standard_of_care_guideline"],
        "evidence_keys": ["named_clinical_guideline"],
        "summary_text": "Patient with chronic hepatitis C was denied sofosbuvir/velpatasvir as not medically necessary until fibrosis advanced.",
    },
    {
        "source_ref": "FIX-010",
        "determination": DETERMINATION_UPHELD,
        "segment": {
            "diagnosis_category": "Digestive System/Gastrointestinal",
            "treatment_category": "Surgery",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Surgery",
        "reasoning_pattern": "BMI and comorbidity documentation did not meet bariatric surgery criteria.",
        "strategy_keys": ["policy_criteria_met"],
        "evidence_keys": ["bmi_and_comorbidity_chart"],
        "summary_text": "Patient seeking sleeve gastrectomy was denied as not medically necessary; plan said BMI and supervised diet history were incomplete.",
    },
    {
        "source_ref": "FIX-011",
        "determination": DETERMINATION_OVERTURNED,
        "segment": {
            "diagnosis_category": "OB-GYN/Pregnancy",
            "treatment_category": "Surgery",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Surgery",
        "reasoning_pattern": "Symptomatic fibroids with anemia justified myomectomy over further medical therapy.",
        "strategy_keys": ["failed_preferred_alternative"],
        "evidence_keys": ["lab_and_imaging"],
        "summary_text": "Patient with heavy bleeding from fibroids was denied myomectomy as not medically necessary after the plan required longer hormonal therapy.",
    },
    {
        "source_ref": "FIX-012",
        "determination": DETERMINATION_UPHELD,
        "segment": {
            "diagnosis_category": "Skin",
            "treatment_category": "Pharmacy",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Pharmacy",
        "reasoning_pattern": "Topical steroids had not been adequately tried for plaque psoriasis.",
        "strategy_keys": ["failed_preferred_alternative"],
        "evidence_keys": ["pharmacy_fill_history"],
        "summary_text": "Patient with plaque psoriasis was denied a biologic as not medically necessary; plan required documented failure of topicals and phototherapy.",
    },
    {
        "source_ref": "FIX-013",
        "determination": DETERMINATION_OVERTURNED,
        "segment": {
            "diagnosis_category": "Neurology",
            "treatment_category": "Diagnostic Imaging",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Diagnostic Imaging",
        "reasoning_pattern": "New focal deficits warranted MRI brain despite a recent CT.",
        "strategy_keys": ["acute_change_in_status"],
        "evidence_keys": ["neurologic_exam"],
        "summary_text": "Patient with new unilateral weakness was denied brain MRI as not medically necessary after a negative CT in the emergency department.",
    },
    {
        "source_ref": "FIX-014",
        "determination": DETERMINATION_UPHELD,
        "segment": {
            "diagnosis_category": "Neurology",
            "treatment_category": "Pharmacy",
            "denial_type": "Experimental/Investigational",
        },
        "service_type": "Pharmacy",
        "reasoning_pattern": "Requested stem-cell infusion for MS is not an established therapy.",
        "strategy_keys": ["peer_reviewed_literature"],
        "evidence_keys": ["published_studies"],
        "summary_text": "Patient with multiple sclerosis was denied autologous stem cell therapy as experimental/investigational.",
    },
    {
        "source_ref": "FIX-015",
        "determination": DETERMINATION_OVERTURNED,
        "segment": {
            "diagnosis_category": "Cardiac/Circulatory",
            "treatment_category": "Surgery",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Surgery",
        "reasoning_pattern": "Significant CAD on cath with ongoing angina on medical therapy met CABG indications.",
        "strategy_keys": ["standard_of_care_guideline"],
        "evidence_keys": ["cath_report"],
        "summary_text": "Patient with three-vessel disease and class III angina was denied CABG as not medically necessary; plan preferred continued medical management.",
    },
    {
        "source_ref": "FIX-016",
        "determination": DETERMINATION_UPHELD,
        "segment": {
            "diagnosis_category": "Cardiac/Circulatory",
            "treatment_category": "Diagnostic Imaging",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Diagnostic Imaging",
        "reasoning_pattern": "Low-risk chest pain did not meet criteria for coronary CTA.",
        "strategy_keys": ["policy_criteria_met"],
        "evidence_keys": ["stress_test_results"],
        "summary_text": "Patient with atypical chest pain was denied coronary CT angiography as not medically necessary after a normal treadmill test.",
    },
    {
        "source_ref": "FIX-017",
        "determination": DETERMINATION_OVERTURNED,
        "segment": {
            "diagnosis_category": "Respiratory",
            "treatment_category": "Durable Medical Equipment",
            "denial_type": "Medical Necessity",
        },
        "service_type": "DME/Prosthetics",
        "reasoning_pattern": "AHI and symptoms met AASM criteria for CPAP.",
        "strategy_keys": ["standard_of_care_guideline"],
        "evidence_keys": ["sleep_study"],
        "summary_text": "Patient with obstructive sleep apnea was denied CPAP as not medically necessary; plan said positional therapy was enough.",
    },
    {
        "source_ref": "FIX-018",
        "determination": DETERMINATION_UPHELD,
        "segment": {
            "diagnosis_category": "Respiratory",
            "treatment_category": "Pharmacy",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Pharmacy",
        "reasoning_pattern": "Asthma was controlled on ICS/LABA; biologics were not indicated.",
        "strategy_keys": ["policy_criteria_met"],
        "evidence_keys": ["spirometry_and_exacerbation_history"],
        "summary_text": "Patient with asthma was denied dupilumab as not medically necessary; plan said exacerbations were infrequent on current inhalers.",
    },
    {
        "source_ref": "FIX-019",
        "determination": DETERMINATION_OVERTURNED,
        "segment": {
            "diagnosis_category": "Autism Spectrum",
            "treatment_category": "Mental Health Treatment",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Mental Health",
        "reasoning_pattern": "ABA hours were supported by a recent assessment showing safety risks and skill deficits.",
        "strategy_keys": ["assessment_supports_intensity"],
        "evidence_keys": ["behavioral_assessment"],
        "summary_text": "Child with autism was denied 25 hours/week of ABA as not medically necessary; plan approved only 8 hours.",
    },
    {
        "source_ref": "FIX-020",
        "determination": DETERMINATION_UPHELD,
        "segment": {
            "diagnosis_category": "Chronic Pain",
            "treatment_category": "Pain Management",
            "denial_type": "Medical Necessity",
        },
        "service_type": "Pain Management",
        "reasoning_pattern": "Repeat lumbar ESI was not indicated without a documented response to prior injections.",
        "strategy_keys": ["failed_preferred_alternative"],
        "evidence_keys": ["procedure_response_notes"],
        "summary_text": "Patient with chronic low back pain was denied a repeat epidural steroid injection as not medically necessary after two prior injections without documented relief.",
    },
]
